spring: 
  profiles:
    active: dev
 
---

spring: 
  profiles: dev
  application:
    name: micorservicecloud-config-eureka-client
eureka: 
  instance: 
    hostname: 127.0.0.1
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ 
    

---

spring: 
  profiles: test
  application:
    name: micorservicecloud-config-eureka-client
eureka: 
  instance: 
    hostname: 127.0.0.1
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ 