spring: 
  profiles:
    active: dev
 
---
server:
  port: 8001
spring: 
  profiles: dev
  application:
    name: micorservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwer223
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  instance:
    instance-id: micorservicecloud-dept8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    

---
server:
  port: 8001
spring: 
  profiles: test
  application:
    name: micorservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwer223
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  instance:
    instance-id: micorservicecloud-dept8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka